

# ServerProperties
server:
  port: 8080
  servlet:
    context-path: /community






# DataSourceProperties

spring:
  datasource:
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 15
      minimum-idle: 5
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lsx-community?characterEncoding=utf-8&useSSL=false
    username: root
    password: "070321"
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
      #encoding: UTF-8
      #content-type: text/html
    mode: HTML5

# MybatisProperties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lsx.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

#logger
logging:
  level:
    com.lsx.community: debug
  file:
    path: D:\Lsx-community\community.log

